"""Version-aware Splunk Enterprise Dashboard Studio generation and validation."""

from splunk_dashboard_studio._version import __version__
from splunk_dashboard_studio.catalog import (
    CatalogEntryNotFound,
    CatalogTargetUnsupported,
    build_catalog_bundle,
    build_catalog_dashboard,
    catalog_entries,
    portable_telemetry_contract,
)
from splunk_dashboard_studio.codec import (
    RoundTripComparison,
    RoundTripDifference,
    StudioView,
    StudioViewCodecError,
    compare_roundtrip,
    decode_view_xml,
    encode_view_xml,
)
from splunk_dashboard_studio.contracts import (
    AgentSkill,
    CatalogEntry,
    DashboardArtifactBundle,
    DashboardEvidenceManifest,
    ObservabilityFramework,
    PanelProvenance,
    RequiredSplunkApp,
    SavedSearchSpec,
    SkillDescriptor,
    SourceTemplateBundle,
    SourceTemplateEntry,
    SourceTemplateLesson,
    SourceTemplateOrigin,
    TelemetryContract,
    TelemetryField,
    TelemetrySignal,
    observability_skill_descriptors,
)
from splunk_dashboard_studio.generation import DashboardBuilder, canonical_json
from splunk_dashboard_studio.graph import (
    GraphAnalysis,
    SearchOptimizationPlan,
    analyze_search_graph,
    plan_search_optimizations,
)
from splunk_dashboard_studio.issues import ValidationIssue, ValidationReport
from splunk_dashboard_studio.models import DashboardDefinition
from splunk_dashboard_studio.profiles import EnterpriseProfile, available_profiles, profile_for
from splunk_dashboard_studio.source_templates import (
    SourceTemplateError,
    SourceTemplateIntegrityError,
    SourceTemplateNotFound,
    SourceTemplateTargetUnsupported,
    build_source_template,
    build_source_template_bundle,
    source_template_entries,
)
from splunk_dashboard_studio.validation import validate_dashboard
from splunk_dashboard_studio.version import EnterpriseVersion, TargetPlatform

__all__ = [
    "AgentSkill",
    "CatalogEntry",
    "CatalogEntryNotFound",
    "CatalogTargetUnsupported",
    "DashboardArtifactBundle",
    "DashboardBuilder",
    "DashboardDefinition",
    "DashboardEvidenceManifest",
    "EnterpriseProfile",
    "EnterpriseVersion",
    "GraphAnalysis",
    "ObservabilityFramework",
    "PanelProvenance",
    "RequiredSplunkApp",
    "RoundTripComparison",
    "RoundTripDifference",
    "SavedSearchSpec",
    "SearchOptimizationPlan",
    "SkillDescriptor",
    "SourceTemplateBundle",
    "SourceTemplateEntry",
    "SourceTemplateError",
    "SourceTemplateIntegrityError",
    "SourceTemplateLesson",
    "SourceTemplateNotFound",
    "SourceTemplateOrigin",
    "SourceTemplateTargetUnsupported",
    "StudioView",
    "StudioViewCodecError",
    "TargetPlatform",
    "TelemetryContract",
    "TelemetryField",
    "TelemetrySignal",
    "ValidationIssue",
    "ValidationReport",
    "__version__",
    "analyze_search_graph",
    "available_profiles",
    "build_catalog_bundle",
    "build_catalog_dashboard",
    "build_source_template",
    "build_source_template_bundle",
    "canonical_json",
    "catalog_entries",
    "compare_roundtrip",
    "decode_view_xml",
    "encode_view_xml",
    "observability_skill_descriptors",
    "plan_search_optimizations",
    "portable_telemetry_contract",
    "profile_for",
    "source_template_entries",
    "validate_dashboard",
]
